import { publicImproveSettingsSource } from '../src/publicImproveSettingsSource.ts';
import { compilePublicBrowserModules } from './public-web-boundary.mjs';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { projectImproveSettingsSources } from '../src/improveSettingsProjection.ts';
import { projectReleasedImprovePolicies } from '../src/improvePolicySources.ts';
import { projectCharacterTargetPresentations } from '../src/characterTargetPresentation.ts';
import { ECHO_STATS_EDITOR_MAX_SUBSTATS } from '../src/echoStatEditor.ts';

const directory = 'docs/ui-prototypes/assets/improve-settings';
const browserDirectory = 'docs/assets';
const browserModules = ['data/echoTubeSource.js', 'resourceInventory.js', 'echoCoreRules.js', 'echoRequirements.js', 'improvePolicyState.js', 'improvePolicyPresentation.js', 'publicSettingsView.js'] as const;
const check = process.argv.includes('--check');
const temporaryDirectory = mkdtempSync(join(tmpdir(), 'bellibing-improve-settings-'));
const compiledDirectory = join(temporaryDirectory, 'assets');
compilePublicBrowserModules(compiledDirectory);

try {
  const files = new Map<string, string>([
    [directory + '/character-targets.mjs', '// Generated by scripts/export-ui-improve-settings.ts. Do not edit.\n'
      + 'export const CHARACTER_TARGET_PRESENTATIONS = ' + JSON.stringify(await projectCharacterTargetPresentations(), null, 2) + ';\n'],
    [directory + '/policies.json', JSON.stringify({ schemaVersion: 1, characters: (await projectReleasedImprovePolicies()).map(publicImproveSettingsSource) }, null, 2) + '\n'],
    [directory + '/sources.json', JSON.stringify({
      schemaVersion: 1,
      generatedFrom: ['src/data/profileCatalogs.ts#PROFILE_REGISTRY', 'src/echoCoreRules.ts#SUBSTAT_TYPES'],
      maxSubstats: ECHO_STATS_EDITOR_MAX_SUBSTATS,
      rollQualityMappingStatus: 'PENDING',
      characters: projectImproveSettingsSources(),
    }, null, 2) + '\n'],
    [directory + '/state.mjs', readFileSync('src/improveSimpleSettings.mjs', 'utf8')],
    ...browserModules.map((name) => [join(browserDirectory, name), readFileSync(join(compiledDirectory, name), 'utf8')] as const),
  ]);

  if (!check) {
    mkdirSync(directory, { recursive: true });
    mkdirSync(browserDirectory, { recursive: true });
  }

  for (const [path, generated] of files) {
    if (check) {
      if (!existsSync(path) || readFileSync(path, 'utf8').replace(/\r\n/g, '\n') !== generated.replace(/\r\n/g, '\n')) {
        throw new Error('Stale Improve Settings export: ' + path);
      }
    } else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, generated);
    }
  }
} finally {
  rmSync(temporaryDirectory, { recursive: true, force: true });
}

console.log('Improve Settings source/state/browser export verified; roll-quality threshold mapping PENDING.');
