import type {
  CharacterBuildPreset,
  EchoLoadoutProfile,
  RotationProfile,
  StatTargetProfile,
  TeamProfile,
  WeaponRecommendationProfile,
} from '../../profileDomain.ts';
import * as CHIXIA from './chixia.ts';
import * as ENCORE from './encore.ts';
import * as LUCILLA from './lucilla.ts';
import * as ROVER_HAVOC from './rover-havoc.ts';
import * as YANGYANG from './yangyang.ts';
import * as MORNYE from './mornye.ts';

// GENERATED by scripts/generate-profile-horizontal-green-lane.mjs. Do not hand-edit.
export const PROFILE_HORIZONTAL_GREEN_LANE_WEAPONS: readonly WeaponRecommendationProfile[] = [...CHIXIA.WEAPONS, ...ENCORE.WEAPONS, ...LUCILLA.WEAPONS, ...ROVER_HAVOC.WEAPONS, ...YANGYANG.WEAPONS, ...MORNYE.WEAPONS];
export const PROFILE_HORIZONTAL_GREEN_LANE_ECHOES: readonly EchoLoadoutProfile[] = [...CHIXIA.ECHOES, ...ENCORE.ECHOES, ...LUCILLA.ECHOES, ...ROVER_HAVOC.ECHOES, ...YANGYANG.ECHOES, ...MORNYE.ECHOES];
export const PROFILE_HORIZONTAL_GREEN_LANE_STATS: readonly StatTargetProfile[] = [...CHIXIA.STATS, ...ENCORE.STATS, ...LUCILLA.STATS, ...ROVER_HAVOC.STATS, ...YANGYANG.STATS, ...MORNYE.STATS];
export const PROFILE_HORIZONTAL_GREEN_LANE_TEAMS: readonly TeamProfile[] = [...CHIXIA.TEAMS, ...ENCORE.TEAMS, ...LUCILLA.TEAMS, ...ROVER_HAVOC.TEAMS, ...YANGYANG.TEAMS, ...MORNYE.TEAMS];
export const PROFILE_HORIZONTAL_GREEN_LANE_ROTATIONS: readonly RotationProfile[] = [...CHIXIA.ROTATIONS, ...ENCORE.ROTATIONS, ...LUCILLA.ROTATIONS, ...ROVER_HAVOC.ROTATIONS, ...YANGYANG.ROTATIONS, ...MORNYE.ROTATIONS];
export const PROFILE_HORIZONTAL_GREEN_LANE_PRESETS: readonly CharacterBuildPreset[] = [...CHIXIA.PRESETS, ...ENCORE.PRESETS, ...LUCILLA.PRESETS, ...ROVER_HAVOC.PRESETS, ...YANGYANG.PRESETS, ...MORNYE.PRESETS];
export const PROFILE_HORIZONTAL_GREEN_LANE_META = {"cohortId":"PROFILE-HORIZONTAL-SEMANTIC-2026-08-31","checkedAt":"2026-08-31","approvedModeCount":6,"approvedCharacterCount":6,"semanticReviewRequired":true,"automationApprovedSemanticTruth":false,"rotationsRemainSourceSequenceOnly":true} as const;
