// AUTO-GENERATED by scripts/sync-echo-game-data.mjs. Do not hand-edit.
export const ECHO_CATALOG_META = {
  "sourceRepository": "DommyMM/wuwabuild",
  "sourceCommit": "0a2e49c649c857c690be709577e6ce98832b2d43",
  "syncedAt": "2026-08-23",
  "echoCount": 181,
  "sonataCount": 34,
  "freshnessGate": "Calamity Effigy"
} as const;
