// AUTO-GENERATED by scripts/sync-echo-game-data.mjs. Do not hand-edit.
import type { SonataGameData } from '../gameDataDomain.ts';

export const SONATA_CATALOG = [
  {
    kind: 'ECHO_SET',
    "id": "sonata-5",
    "name": "Celestial Light",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 5,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Spectro DMG + 10%."
      },
      {
        "pieces": 5,
        "description": "Spectro DMG + 30% for 15s after releasing Intro Skill."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-28",
    "name": "Chromatic Foam",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 28,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Fusion DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "When the Resonator inflicts Fusion Burst on the enemies, they gain the following effects: Gain {0} Fusion DMG Bonus for {1} s. While this effect is active, casting an Outro Skill grants the incoming Resonator {2} Fusion DMG Bonus for {3}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-20",
    "name": "Crown of Valor",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 20,
    "activationPieces": [
      3
    ],
    "rawPieceEffects": [
      {
        "pieces": 3,
        "description": "Upon gaining a Shield, increase the Resonator's ATK by {0} and Crit. DMG by {1} for {3}s. This effect can be triggered once every {4}s and stacks up to {2} times."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-19",
    "name": "Dream of the Lost",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 19,
    "activationPieces": [
      3
    ],
    "rawPieceEffects": [
      {
        "pieces": 3,
        "description": "Holding {0} Resonance Energy increases Crit. Rate by {1} and grants {2} Echo Skill DMG Bonus."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-13",
    "name": "Empyrean Anthem",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 13,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Energy Regen + {0}"
      },
      {
        "pieces": 5,
        "description": "Increase the Resonator's Coordinated Attack DMG by {0}. Upon a critical hit of Coordinated Attack, increase the active Resonator's ATK by {1} for {2}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-11",
    "name": "Eternal Radiance",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 11,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Spectro DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "Inflicting Spectro Frazzle on enemies increases Crit. Rate by {0} for {1}s. Attacking enemies inflicted with {2} stacks of Spectro Frazzle grants {3} Spectro DMG Bonus for {4}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-22",
    "name": "Flamewing's Shadow",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 22,
    "activationPieces": [
      3
    ],
    "rawPieceEffects": [
      {
        "pieces": 3,
        "description": "Dealing Echo Skill DMG increases Heavy Attack Crit. Rate by {0} for {1}s. Dealing Heavy Attack DMG increases Echo Skill Crit. Rate by {2} for {3}s. While both effects are active, gain {4} Fusion DMG Bonus."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-18",
    "name": "Flaming Clawprint",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 18,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Fusion DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "Casting Resonance Liberation grants all Resonators in the team {0} Fusion DMG Bonus and the caster {1} Resonance Liberation DMG Bonus, lasting for {2}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-1",
    "name": "Freezing Frost",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 1,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Glacio DMG + 10%."
      },
      {
        "pieces": 5,
        "description": "Glacio DMG + 10% after releasing Basic Attack or Heavy Attack. This effect stacks up to 3 times, each stack lasts 15s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-10",
    "name": "Frosty Resolve",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 10,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Resonance Skill DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "Casting Resonance Skill grants {0} Glacio DMG Bonus for {1}s and casting Resonance Liberation increases Resonance Skill DMG by {2}, lasting for {3}s. This effect stacks up to {4} times."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-16",
    "name": "Gusts of Welkin",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 16,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Aero DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "Inflicting Aero Erosion upon enemies increases Aero DMG for all Resonators in the team by {0}, and for the Resonator triggering this effect by an additional {1}, lasting for {2}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-25",
    "name": "Halo of Starry Radiance",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 25,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Healing Bonus + {0}."
      },
      {
        "pieces": 5,
        "description": "When healing a Resonator in the team, every {0} of Off-Tune Buildup Rate grants a {1} ATK increase to all Resonators in the team for {3}s, up to {2}. Effects of the same name cannot be stacked."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-6",
    "name": "Havoc Eclipse",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 6,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Havoc DMG + 10%."
      },
      {
        "pieces": 5,
        "description": "Havoc DMG + 7.5% after releasing Basic Attack or Heavy Attack. This effect stacks up to 4 times, each stack lasts 15s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-34",
    "name": "Heart of Evil's Purge",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 34,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Aero DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "Inflicting Tune Strain - Shifting increases Crit. DMG by {0} and Aero DMG Bonus {1} for {2}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-35",
    "name": "Lamp of Nether Road",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 35,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "HP + {0}"
      },
      {
        "pieces": 5,
        "description": "Upon gaining a Shield, gain {0} increase in Crit. Rate for {2}, max {1} stacks. This effect can be triggered every {3}s. At max stacks, gain {4} Fusion DMG Bonus."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-21",
    "name": "Law of Harmony",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 21,
    "activationPieces": [
      3
    ],
    "rawPieceEffects": [
      {
        "pieces": 3,
        "description": "Casting Echo Skill grants {0} Heavy Attack DMG Bonus to the caster for {1}s.\nAdditionally, all Resonators in the team gain {2} Echo Skill DMG Bonus for {4}s, stacking up to {3} times. Echoes of the same name can only trigger this effect once. The record of Echo triggering this effect is cleared along with this effect. At {3} stacks, casting Echo Skill again resets the duration of this effect."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-9",
    "name": "Lingering Tunes",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 9,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "ATK +10%"
      },
      {
        "pieces": 5,
        "description": "While on the field, ATK increases by 5% every 1.5s. This effect stacks up to 4 times. Outro Skill DMG + 60%."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-12",
    "name": "Midnight Veil",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 12,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Havoc DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "When Outro Skill is triggered, deal additional {0} Havoc DMG to surrounding enemies, considered Outro Skill DMG, and grant the incoming Resonator {1} Havoc DMG Bonus for {2}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-2",
    "name": "Molten Rift",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 2,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Fusion DMG + 10%."
      },
      {
        "pieces": 5,
        "description": "Fusion DMG + 30% for 15s after releasing Resonance Skill."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-8",
    "name": "Moonlit Clouds",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 8,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Energy Regen + {0}."
      },
      {
        "pieces": 5,
        "description": "Upon using Outro Skill, increases the ATK of the next Resonator by 22.5% for 15s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-24",
    "name": "Pact of Neonlight Leap",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 24,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Spectro DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "Casting Outro Skill increases the ATK of the incoming Resonator who casts Intro Skill by {0}. Each point of Tune Break Boost the incoming Resonator has additionally increases their ATK by {1}, up to {2}. This effect lasts for {3}s, or until the Resonator is switched out."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-31",
    "name": "Reel of Spliced Memories",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 31,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "ATK + {0}"
      },
      {
        "pieces": 5,
        "description": "Inflicting Tune Rupture - Shifting or Tune Strain - Shifting on enemies increases the Tune Break Boost of Resonators in the team by {0} for {1}s. Effects of the same name do not stack."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-7",
    "name": "Rejuvenating Glow",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 7,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Healing Bonus + 10%."
      },
      {
        "pieces": 5,
        "description": "Increases the ATK of all party members by 15% for 30s upon healing allies."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-26",
    "name": "Rite of Gilded Revelation",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 26,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Spectro DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "Dealing Basic Attack DMG increases Spectro DMG by {0} for {2}s, stacking up to {1} times. With {1} stacks, casting Resonance Liberation grants {3} Basic Attack DMG Bonus."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-32",
    "name": "Shadow of Shattered Dreams",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 32,
    "activationPieces": [
      1
    ],
    "rawPieceEffects": [
      {
        "pieces": 1,
        "description": "Inflicting Hack - Shifting on the target grants {1} Basic Attack DMG Bonus and Heavy Attack DMG Bonus for {2}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-4",
    "name": "Sierra Gale",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 4,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Aero DMG + 10%."
      },
      {
        "pieces": 5,
        "description": "Aero DMG + 30% for 15s after releasing Intro Skill."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-33",
    "name": "Song of Feathered Trace",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 33,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Energy Regen + {0}"
      },
      {
        "pieces": 5,
        "description": "Upon inflicting Havoc Bane, gain Xuanling's Feather, which grants a {0} increase in Crit. Rate and {1} increase in Heavy Attack DMG Bonus to the Resonator, lasting {2}s.\nUpon inflicting Glacio Chafe, gain Chongming's Feather, which grants a {4} increase in ATK to Resonators in the team for every {3} of the Resonator's Energy Regen, up to {5}, lasting {6}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-29",
    "name": "Sound of True Name",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 29,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Aero DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "Dealing Echo Skill DMG to enemies increases the Resonator's Echo Skill Crit. Rate by {0}, and grants {1} Aero DMG Bonus for {2}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-23",
    "name": "Thread of Severed Fate",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 23,
    "activationPieces": [
      3
    ],
    "rawPieceEffects": [
      {
        "pieces": 3,
        "description": "Inflicting Havoc Bane increases the Resonator's ATK by {0} and grants {1} Resonance Liberation DMG Bonus for {2}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-14",
    "name": "Tidebreaking Courage",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 14,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Energy Regen + {0}"
      },
      {
        "pieces": 5,
        "description": "Increase the Resonator's ATK by {0}. Reaching {1} Energy Regen increases all Attribute DMG by {2} for the Resonator."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-27",
    "name": "Trailblazing Star",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 27,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Fusion DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "Inflicting Fusion Burst or Tune Rupture - Shifting increases the Resonator's Crit. Rate by {0} and grants {1} Fusion DMG Bonus for {2}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-3",
    "name": "Void Thunder",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 3,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Electro DMG + 10%."
      },
      {
        "pieces": 5,
        "description": "Electro DMG + 15% after releasing Heavy Attack or Resonance Skill. This effect stacks up to 2 times, each stack lasts 15s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-17",
    "name": "Windward Pilgrimage",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 17,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Aero DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "Hitting a target with Aero Erosion increases Crit. Rate by {0} and grants {1} Aero DMG Bonus, lasting for {2}s."
      }
    ]
  },
  {
    kind: 'ECHO_SET',
    "id": "sonata-30",
    "name": "Wishes of Quiet Snowfall",
    "releaseStatus": "RELEASED",
    "verificationStatus": "PARTIALLY_VERIFIED",
    "integrationStatus": "DATA_ONLY",
    "provenance": {
      "sourceLabels": [
        "wuwabuild normalized game-data snapshot",
        "Wuthery / Encore upstream raw game data"
      ],
      "sourceUrls": [
        "https://github.com/DommyMM/wuwabuild/tree/0a2e49c649c857c690be709577e6ce98832b2d43/public/Data",
        "https://api-v2.encore.moe/api",
        "https://files.wuthery.com"
      ],
      "checkedAt": "2026-08-23",
      "notes": [
        "Bellibing imports only a compact raw identity snapshot; upstream combat/scoring code is not copied.",
        "Raw effect text is stored for audit only; it is not a modeled trigger/uptime/stacks implementation."
      ]
    },
    "sourceId": 30,
    "activationPieces": [
      2,
      5
    ],
    "rawPieceEffects": [
      {
        "pieces": 2,
        "description": "Glacio DMG + {0}"
      },
      {
        "pieces": 5,
        "description": "Inflicting Glacio Chafe on enemies increases Glacio DMG dealt by {0} for {1}s. The Resonator gains the Snowfall effect for {11}s, which can be triggered once every {2}s. While Snowfall is active:\n- Dealing Resonance Liberation DMG removes Snowfall and increases the Resonator's Crit. Rate by {4} for {5}s. While the effect is active, dealing Resonance Liberation DMG extends its duration by {8}s, triggered once every {9}s, up to {10} times.\n- Casting Outro Skill removes Snowfall and grants {6} Glacio DMG Bonus to the incoming Resonator for {7}s.\nWhen Snowfall is removed, only one of the effects above can be triggered."
      }
    ]
  }
] as const satisfies readonly SonataGameData[];
